spring:
  application:
    name: auth-core
  datasource:
    url: jdbc:mysql://localhost:3306/member
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mem:
  core:
    group-id: 1
    work-id: 1
    cache: false #控制是否开启redis缓存
  cache:
    enable: true

mybatis:
  mapper-locations: classpath*:com/index/mapper/*.xml

pagehelper:
  auto-dialect: true
  offset-as-page-num: true
  reasonable: true
  page-size-zero: true

logging:
  level:
    root: debug
